seafloor-geodesy/gnatss

README.md

This PR updates badge to documentation build within ReadTheDocs. The initial jupyterbook docs setup can be found in commit https://github.com/uw-ssec/offshore-geodesy/commit/8f989bb242795ef9b18026db0f5302783342b43e. Additionally, PR https://github.com/uw-ssec/offshore-geodesy/pull/56 updates reference to `offshore-geodesy` to be `seagap` instead. 
- #51

Update badge to docs

---

.flake8
seagap/configs/main.py
seagap/configs/solver.py

This PR adds configs modules for setting up the main configuration file data validation and settings management.
The fields are based on the original master configuration file. This PR uses [pydantic](https://docs.pydantic.dev/) technology to define the configurations.
@johnbdesanto could you go through the descriptions and ensure that I have the accurate text for the fields? Please focus on the solver configuration. Also, if you have another name for this too, please let me know.
```
2022-09-28 00:00:00
3
0    08       45.302064471    -124.978181346   -1176.5866      0.200000d0       1481.551 
1    12       45.295207747    -124.958752845   -1146.5881      0.320000d0       1481.521 
2    22       45.309643593    -124.959348875   -1133.7305      0.440000d0       1481.509 
6378137.d0 …
```

Setup initial configuration file spec for solver

---

.github/workflows/test.yaml
seagap/configs/io.py
seagap/configs/main.py
seagap/configs/solver.py
seagap/utilities/io.py
setup.cfg
tests/utilities/test_io.py

This PR adds I/O utility functions and also add `sound_speed`, `travel_times`, and `gps_positions` path configuration. Additionally, this PR adds a way to input `distance_limit` and `residual_limit` values to the solver configuration.
```
solver:
...
input_files:
sound_speed:
path: /path/to/ctd/CTD_NCL1_Ch_Mi
storage_options: {}
travel_times:
path: /some/pxp_data/dir/**/pxp_tt
storage_options: {}
gps_positions:
path: /some/gps_data/dir/**/POS_FREED_TRANS_TWTT
storage_options: {}
output:
path: /some/output/dir
storage_options: {}
```
- #19 
- #21

Add io utilities and io configurations to YAML spec

---

.readthedocs.yml

This PR removes the need to install with setuptools since we're using hatch here.

Remove setuptools python install for readthedocs

---

src/gnatss/loaders.py

The travel times files `pxp_tt` has 2 separate structures, which is stored in another file called `pxp_tt_j2k`. This file already has the time component as J2000 epoch time float and need to be handled. This update come about after conversation with @johnbdesanto yesterday. The change included in this PR is having an `is_j2k` flag, so that if this is `True` it means that we are expecting the `pxp_tt_j2k` file rather than the `pxp_tt`.

Update load travel times to include j2000

---

.gitignore
docs/_config.yml
docs/_toc.yml
docs/api.rst
docs/configs.rst
pyproject.toml
src/gnatss/loaders.py

This PR exposes the docstrings for the modules to jupyterbook docs.

Add docstring to jupyter book

---

.github/dependabot.yml
.github/workflows/test.yaml
.readthedocs.yml
pyproject.toml
src/gnatss/loaders.py

This PR bumps the minimum python version to 3.9 to stay up to date since it's still supported until october of this year. Additionally, this pins dependencies max versions to prevent things from breaking from future releases.

Bump min py >= 3.9 and pin dependencies max

---

tests/utilities/test_io.py

Hi @lsetiawan ,
I've added a new parameter to the pytest.fixture called "no_files_found". In this case, I'm creating a unique directory path that does not exist in the filesystem, which is represented by the file_path. This scenario will ensure that the glob operation doesn't find any files matching the pattern, and thus, the test case for no files found during the glob operation will be covered.
With this modification, when running the tests, the test suite will include the missing test case, and the code coverage analysis should no longer show a missing coverage for that particular scenario. I am looking forward to your review!

test(utilities): add test case to return False when checking files

---

tests/test_harmonic_mean.py

Hi @lsetiawan ，
I've finished L1 task (Offshore Geodesy - Add test case to raise ValueError) and added two new test cases in tests/test_harmonic_mean.py. One test case error reported by the unit test has been fixed.
test_sv_harmonic_mean_invalid_input: This test case checks if the sv_harmonic_mean function raises a ValueError when provided with an invalid end_depth input (in this case, a string instead of a float or integer).
test__compute_hm_invalid_input: This test case checks if the _compute_hm function raises a ValueError when provided with an invalid end_depth input (in this case, a string instead of a float or integer).
These test cases will ensure that the ValueError scenarios in both sv_harmonic_mean and _compute_hm functions are properly covered during testing.
Reference: …

test(seagap): add test case to raise ValueError

---

src/gnatss/utilities/time.py
tests/utilities/test_time.py

* Add unittest to verify working of custom subclass "TimeUnixJ2000" of astropy's "TimeFromEpoch".
* Linked to issue [uw-ssec/codeuw/issues/29](https://github.com/uw-ssec/codeuw/issues/29)

Offshore Geodesy - Add testing for the time.py utility module

---

noxfile.py

This PR adds the use of [`nox`](https://nox.thea.codes/en/stable/) for ease of development by creating a `noxfile.py` configuration.

ci: add noxfile to use nox for ease of development

---

.github/workflows/ci.yaml
README.md

This PR changes the CI name from `Test` to `CI`, adds a pytest annotation capability and update README to reflect change.

ci: add test annotations and change workflow name

---

src/gnatss/loaders.py

This PR sets the scale of the datetime string to Terrestrial Time (`tt`) by default so it can convert properly to J2000.
Closes #116

fix: update time scale to 'tt' as default assumption

---

README.md
src/gnatss/cli.py

This PR adds docs about the CLI to the README, and cleans up the extra unecessary docstring in the run function, since a dynamically generated text is displayed automatically from the function inputs already.
Closes #131

docs: add doc about CLI and clean terminal doc for CLI

---

pyproject.toml
src/gnatss/configs/io.py
src/gnatss/configs/main.py
src/gnatss/configs/solver.py
src/gnatss/loaders.py

This PR refactor the pydantic models to use Pydantic version 2 and its best practices. Additionally, the version for `autodoc_pydantic` is now bumped to 2 as well.
Closes #85

refactor: update codebase to use Pydantic v2

---

src/gnatss/cli.py
src/gnatss/constants/__init__.py
src/gnatss/main.py

Added a flag in cli for extracting the distance from center of the array called '--extract-dist-center'. This introduces an important function in 'main.py' called 'extract_distance_from_center' for performing east,north,up computation w.r.t array center,
azimuth and distance. A file called 'dist_center.csv' is also exported when this flag is active.
---
Ref: Issue #137

feat: Add distance from center computation

---

src/gnatss/configs/main.py
src/gnatss/configs/posfilter.py
tests/configs/test_main.py
tests/configs/test_posfilter.py
tests/conftest.py

This PR adds configuration pydantic model for future position filtering routine. At the moment, it adds a way to pass in the Roll Pitch Heading data.
Closes #129

feat(posfilter): Adds config model for Position Filtering

---

src/gnatss/cli.py

Added optional CLI flags '--distance-limit' and '--residual-limit' to short-circuit any pydantic way to set those values such as environment variables or the values in config yaml.
--------
Ref: Issue #142

feat: Add flags to override 'residual' and 'distance'

---

src/gnatss/constants/__init__.py
src/gnatss/loaders.py
src/gnatss/main.py
tests/test_main.py

This PR introduces 2 things:
- A new `load_roll_pitch_heading` method to load RPH file(s)
- A new `proc` argument to `gather_files` method so that it can grab paths for the `posfilter` process
Closes #118

feat(loaders): Add loader function for RPH and flexible file gathering

---

src/gnatss/cli.py
src/gnatss/configs/io.py
src/gnatss/loaders.py
src/gnatss/main.py
tests/test_main.py

This PR contains features to figure out residual outliers based on the `residual_limit` value as distance from center outlier from the `distance_limit` value. Additionally those outliers are now removed from the overall data before solve happens. In the case of residual outliers, this will be exported to `outliers.csv` file in the output directory specified by the user. During the `load_deletions` step, this `outliers.csv` file will be searched in the output directory, if it exists, then it will be included to the rest of the routine be removing those data from the input data for the solver routine.
This functionality mirrors:
```csh
proc_dist_del.csh           dist_center  $dist_limit
proc_outlier_del.csh                            {$label}_{$i}_{$j}_{$k}_{$l} $residual_limit
```
Closes …

feat: Add feature to export and use outliers

---

src/gnatss/configs/io.py

Added a check for output path string to endwith '/' which signifies that this is a directory rather than a file. Always ensure that output path exists by creating it if it doesn't exist.

fix(io): Add a catch for directory only path

---

src/gnatss/configs/main.py
src/gnatss/configs/solver.py
src/gnatss/utilities/geo.py

Added 'ecef2ae' function to compute azimuth and elevation. Additionally, 'azimuth' and 'elevation' properties are now added to the 'SolverTransponder' object on instantiation.

feat: Added azimuth and elevation calc

---

.gitignore
tests/test_loaders.py

* Improve test coverage for loaders.py load_configuration()
* Add .idea files to gitignore

test(loaders): Add test for load_configuration

---

tests/test_loaders.py

* Improve unittest coverage for gnatss.loaders `load_sound_speed` function.
* Issue #124

test(loaders): Add test for load_sound_speed

---

src/gnatss/cli.py
src/gnatss/configs/solver.py
src/gnatss/constants/__init__.py
src/gnatss/main.py

This PR adds input for outlier threshold, so that a `RuntimeError` can be raised when outliers exceed the number of data. Additionally, modified the original residual limit to 10000.0
---
Ref: #170

feat: Add input for outlier threshold

---

src/gnatss/cli.py
src/gnatss/ops/qc.py

This PR initialized qc module and residual plotting functionality such as plotting the ENU components and residuals together with outliers/deletions flagging.
Issue #149 
Issue #148

feat: Add Residual Plotting Functionality

---

tests/data/config.yaml
tests/test_loaders.py

* Add unittest coverage for loaders.py load_travel_times()
* Issue -> https://github.com/uw-ssec/offshore-geodesy/issues/125

test(loaders): Add test for load_travel_times #125

---

src/gnatss/loaders.py
tests/test_loaders.py

* Add new unittest `test_load_deletions()` to increase `loaders.py` coverage.

test(loaders): Add test for load_deletions #127

---

src/gnatss/harmonic_mean.py
tests/test_harmonic_mean.py

Added '_sv_harmon_mean' numba implementation for
calculating harmonic mean that uses calculations
used within the original fortran code to get same
harmonic values. Now there's a 'method' value for the main 'sv_harmonic_mean' function that allows user
to switch back and forth b/w the two methods.
---
Ref #193

feat: Add numba harmonic mean implementation

---

README.md

Update the codecov links and other links that point to uw-ssec to the current organization.

docs: Update codecov and links

---

src/gnatss/main.py

Adds a "session_time" attribute to the process NetCDF file based on a calculation of median time from the residuals.
```
Attributes:
session_time :
2022-08-02T13:00:00
```

feat: Add session_time attribute to process dataset

---

docs/intro.md

Add a small section in the main intro page of the documentation page about the benchmarking repository and main jupyter notebook.

docs: Add a small section about the benchmarking

---

README.md
src/gnatss/cli.py

* Linked to Issue #208
* Make extract-dist-center, extract-process-dataset, and qc CLI arguments default to True

refactor: Update run flags for distance center, process dataset, and qc

---

src/gnatss/loaders.py
tests/test_loaders.py

Removed the exception to ignore 'parsed' files
since now users can separate these files in a separate directory instead and specify that in the config yaml.
---
Ref: https://github.com/seafloor-geodesy/gnatss/issues/214

fix: Fixed the ignoring of 'parsed' files

---

MANIFEST.in
pyproject.toml

* MANIFEST.in file is used only when using the setuptools build system. However as mentioned in the pyproject.toml we are using hatchling build system instead. We can therefore remove this MANIFEST file.
* Exclude the ./tests directory from the build step. the source distribution file reduced in size significantly. This speeds up gnatss pip installation speed due to faster downloading, and lesser unzipping.
* Solves Issue #220

(build): Need a config to ignore test data

---

src/gnatss/cli.py
src/gnatss/constants/__init__.py
src/gnatss/loaders.py
src/gnatss/main.py
tests/test_loaders.py

* Currently roll-pitch-heading loader function only accepts [time, roll, pitch, heading] rows. It should accept optional covariance rows "roll-roll", "roll-pitch", "roll-heading" ... .etc in the csv file as well.
* Add helper function gather_files_all_procs() that gathers file paths from all processes
* * Issue #222

feat(posfilter): roll-pitch-heading loader function should accept optional covariance rows

---

src/gnatss/utilities/time.py
tests/utilities/test_time.py

This PR introduces a utility function `gpsws_to_time` for converting from GPS Week and Seconds to Astropy Time object. Additionally, some refactoring is done to the `test_time.py`.
Closes #229

feat: Add 'gpsws_to_time' function to convert GPS Week, Seconds to Astropy Time

---

.github/workflows/cd.yml

Manual duplicate of https://github.com/seafloor-geodesy/gnatss/pull/228

chore(deps): Bump pypi publish from 1.8.11 to 1.8.14

---

src/gnatss/configs/solver.py
src/gnatss/solver/methods.py
src/gnatss/solver/run.py
src/gnatss/solver/solve.py
src/gnatss/solver/utilities.py

This PR add ability to extend the `calc_twtt_model` function and configuration of `twtt_model` for the `solver`. However, it is currently only "simple_twtt" that's available.

refactor: Extend calc_twtt_model to allow other methods

---

src/gnatss/loaders.py
src/gnatss/posfilter/__init__.py
tests/conftest.py
tests/posfilter/test_posfilter.py
tests/test_loaders.py

* Write unittests for posfilter `rotation` and `kalman_filtering` functions
* Improve test coverage
* For Kalman Filtering:
* Test Reference GPS_GEOCENTRIC cols in reference should match solutions ANT_GPS_GEOCENTRIC cols within 1cm tolerance
* Square root of ANT_GPS_COV_DIAG values should lie between 0.5cm to 5cm
* For Rotation:
* A maximum of 2.5% of rows can exceed the 1cm tolerance between the solutions and reference GPS_GEOCENTRIC cols  
* Completes Issue #121

test(posfilter): Add Unittests for posfilter rotation and kalman filtering functionalities

---

src/gnatss/utilities/testing.py
tests/test_main.py
tests/utilities/test_geo.py
tests/utilities/test_testing.py

* Uncomment testcases in `test_geo.py`
* Add unittests for download_test_data()
* Add end to end run_gnatss() unittest
* Overall increase of project unittest coverage from 50% to 75.9%
* Related to Issue #261

test: Increase Project Unittest coverage from 50% to 75.9%

---

.pre-commit-config.yaml
docs/gnssa_preprocessing.md

This PR fixes the issue with pre-commit reformating `_{` to `*{` causing the rendering to not work properly as mentioned in https://github.com/seafloor-geodesy/gnatss/pull/290#issuecomment-2195621060

docs: Fix latex formatting, and ignore file

---

src/gnatss/ops/data.py
src/gnatss/solver/utilities.py

This should address Issue #296.
I have chosen to directly compare the number of replies to the number of transponders for two reasons:
1) I'm trying to lay groundwork to allow the software to handle arrays with >3 transponders.
2) I'm trying to insulate the software from a theoretical bug where a large enough array makes it difficult (if not impossible) for every transponder to reply to a single ping, as was hinted at by @SquirrelKnight. If we tie the comparison to the max replies to a ping then that failure avenue is left open
This is a temporary fix, and in the future I think we should relax this constraint by making it optional. This would open the door to gnatss being able to process data from arrays described in point 2 above.

fix: Ignore pings without replies from every transponder

---

src/gnatss/ops/data.py
src/gnatss/ops/io.py
src/gnatss/solver/utilities.py

This is a one-line fix that solves an issue where setting the "--from-cache" flag would not prevent gnatss from loading input files declared in the posfilter mode of the config file. Since some of these files are large (INSPVAA and INSSTDEVA files can be 10s of Gb) this saves a noticeable amount of processing time when --from-cache is set.
The actual functionality of gnatss when --from-cache is declared is not affected since it only runs the solver. Posfilter operations are not performed in this case.
Gnatss can still be run in posfilter mode when --from-cache is not declared, either by declaring --posfilter or by default.

fix: Set posfilter files to no longer load when --from-cache set

---

.github/workflows/ci.yaml
noxfile.py
pyproject.toml

This PR fixes the current failing tests caused by deprecation of disutils: https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration... Due to this deprecation, the build backend for f2py is now meson: https://numpy.org/doc/stable/f2py/buildtools/meson.html. For now, we are just pinning versions to ensure that the software is not failing. Future migrations will be needed to support newer versions of numpy.

ci: Fix failing ci tests due to deprecated disutils

---

src/gnatss/ops/data.py
src/gnatss/solver/run.py
src/gnatss/solver/utilities.py

This pr should fix the bug highlighted in issue #341. Specific changes include:
-prefilter subroutine that removes pings with replies<num_transponders has been moved out of prepare_and_solve() and into run_solver(), which should allow it to execute before the creation of the all_epochs variable that controls residual timestamps.
-In case there remains a difference in the number of epochs and the number of residuals, a check has been implemented before residual flagging that will trigger an error if they do not match. I do not expect this to ever trigger without further modification to the code, but in case a similar issue arises in the future I hope this will make it much easier to identify. (This was a silent bug.)
-I have moved the prefilter code from ops/data.py to solver/utilities.py …

fix: Fix residual desync

---

.github/workflows/ci.yaml
noxfile.py
pyproject.toml

This pull request introduces updates to the CI pipeline, dependency management, and build/test configurations to support newer Python versions and modernize the toolchain. The most significant changes include expanding Python version support, updating dependencies, and migrating to the Meson build system for Fortran extensions.
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL20-R20): Added support for Python 3.12 and 3.13 in the CI matrix to ensure compatibility with newer Python versions.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L23-R31): Updated `astropy` dependency to `>=6.1.7,<8` and `numpy` dependency to `>1.26,<2` to align with the latest library versions …

chore(deps): Update dependencies for np>1.26

---

src/gnatss/loaders.py
src/gnatss/ops/qc.py

This PR resolves errors triggered by ruff, which was complaining that there were dependency declarations mid-function instead of at the file header in loaders.py and ops/qc.py. I have moved the declarations to the header.
Note that the declaration in ops/qc.py was importing functions defined in the same file, which seemed strange (and triggered another error from the header) so I completely deleted that line. After running a data processing test I believe that this should not be causing any issue, but I will document it here in case it does cause problems in the future.

chore: declarations to header
