seafloor-geodesy/gnatss

.github/workflows/test.yaml
This PR adds code coverage report in CI and push the report to codecov.
=> Add coverage report and upload to codecov

src/gnatss/cli.py, src/gnatss/main.py
This PR updates the cli module to separate a lot of the computation code and the main function to main module.
=> Update CLI by separating to main module

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/noop.txt, .pre-commit-config.yaml
This PR adds devcontainer configuration
=> Add codespaces configuration

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This PR updates the codespace packages and install the jupyter and python extension for vscode
=> Update codespace to install package and ipykernel

src/gnatss/main.py, src/gnatss/utilities/io.py, tests/test_main.py
This PR adds additional docstring and start testing `main.py`. There are still various functions in that module to be tested, but I added a simple test for gather files since I can simply mock that.
=> Add docstring and initial test for main.py

src/gnatss/utilities/geo.py, tests/utilities/test_geo.py
This PR add the only function in geo module that gets the rotation matrix.
=> test(geo): add test for geo module

.github/CONTRIBUTING.md
This PR adds contributing documentation.
=> docs: add CONTRIBUTING docs for setting up dev

README.md
This PR updates the repo README file with the up to date text and links as well as pointing to the escience's website about the project.
=> docs: update repo readme

README.md
Added codefactor badge to show code quality score. This is free for open source software.
See: https://www.codefactor.io/ for more info.
Closes #135
=> docs(readme): Add codefactor badge

pyproject.toml, src/gnatss/cli.py, src/gnatss/main.py
This PR introduces a way to export the processing results into a netcdf file.
This closes #86
=> feat: Add a feature to extract and save process results to netcdf file

.github/workflows/cd.yml, pyproject.toml
This PR sets up continuous development for the package
=> ci: Update dev versioning and add cd yaml

README.md, src/gnatss/cli.py, src/gnatss/configs/io.py, src/gnatss/configs/solver.py, src/gnatss/loaders.py, src/gnatss/main.py, tests/data/config.yaml
Changed code routine to create 'deletions.csv' on each run
of the solve routine. This is created from the outliers found
after specifying the residual limits. This file is used
to filter out outliers within the dataset.
Additionally, the program will now by default extract the
residuals.csv file and compute the distance from center outliers.
=> Update to use deletions.csv file internally

tests/test_loaders.py
* Add unittest coverage for `loaders.py` `load_gps_solutions()`.
* Issue https://github.com/uw-ssec/offshore-geodesy/issues/126
=> test(loaders): Add test for load_gps_solutions #126

src/gnatss/main.py, tests/test_main.py
Fixes the case of final solution message showing
only the third transponder rather than the final
solution data for all 3 transponders.
This is done by extracting to a private print_final_stats function.
---
Ref #178
=> fix: Fix runtime message that shows wrong info

src/gnatss/main.py
This PR adds geoid undulation adjustment for the final height value.
Fixes #191
=> fix: Add geoid undulation for final height

README.md
Update the links for codefactor and ci badges to the new seafloor geodesy org location.
=> docs: update codefactor and ci badge

src/gnatss/loaders.py, tests/test_loaders.py
This PR fixes the deprecated `delim_whitespace` for Pandas
`Deprecated since version 2.2.0`
=> fix: Fix deprecated delim_whitespace with sep for pandas

src/gnatss/main.py, src/gnatss/ops/data.py, src/gnatss/ops/posfilter.py
This PR adds spline interpolation method and update travel times clean up to separate functions b/w clean up and filtering.
=> feat: Add spline interp and update ops for tt

src/gnatss/cli.py, src/gnatss/configs/main.py, src/gnatss/configs/posfilter.py, src/gnatss/configs/solver.py, src/gnatss/configs/transponders.py, src/gnatss/constants/__init__.py, src/gnatss/constants/garpos.py, src/gnatss/dataspec/__init__.py, src/gnatss/dataspec/base.py, src/gnatss/dataspec/utils.py, src/gnatss/dataspec/v1.py, src/gnatss/loaders.py, src/gnatss/main.py, src/gnatss/ops/data.py, src/gnatss/ops/posfilter.py, src/gnatss/ops/solve.py
This PR updates the configuration to be able to handle config for both posfilter and solver so that an end-to-end pipeline can be run. Additionally, data specification object has been added, which has the fields that matches specification outlined in https://hal.science/hal-04319233/document, which in this case is called version "v1". Lastly an initial `run_e2e` function is introduced to be able to perform data processing from an L1 novatel data all the way to solver, though this is currently a WIP.
=> feat: Configuration updates, adding data spec, and initial end-to-end function

src/gnatss/cli.py, src/gnatss/configs/io.py, src/gnatss/configs/posfilter.py, src/gnatss/configs/solver.py, src/gnatss/loaders.py, src/gnatss/main.py, src/gnatss/ops/data.py, src/gnatss/ops/harmonic_mean.py, src/gnatss/ops/io.py, src/gnatss/ops/qc.py, src/gnatss/ops/validate.py, src/gnatss/posfilter/posfilter.py, src/gnatss/posfilter/run.py, src/gnatss/posfilter/utilities.py, src/gnatss/solver/run.py, src/gnatss/solver/solve.py, src/gnatss/solver/utilities.py
This PR performs a large refactoring overhaul of the codebase so that it's more modular and clear. The `posfilter` and `solver` processes are now it's own module consisting of a couple files: `run.py`, `<process>.py`, and `utilities.py`. This is now a pretty consistent pattern within the package to allow for clarity:
- `run.py`: This is where code for the various steps in running that process are called.
- `<process>.py`: This is called `posfilter.py` for `posfilter` and `solve.py` for solver. This is code that does the heavy lifting of processing for that particular process, essentially this was moved from the `ops` module.
- `utilities.py`: This is a home to any utility functions that support the `<process>.py` or others for that particular process module.
Additionally, The end to end …
=> refactor: A large refactor of codebase to ensure more modularity and clarity

.github/workflows/cd.yml, .github/workflows/ci.yaml
Manual duplicate of https://github.com/seafloor-geodesy/gnatss/pull/234
=> chore(deps): Bump setup python from 5.0 to 5.1

src/gnatss/cli.py, src/gnatss/loaders.py, src/gnatss/main.py, src/gnatss/ops/data.py, src/gnatss/ops/io.py, src/gnatss/solver/utilities.py
This PR adds additional flags of `--run-all`, `--posfilter`, `--solver` to specific process to run without having to comment out config files
=> feat: Fix and add flags to be able to skip steps

src/gnatss/cli.py
This PR fixes #246 by adding `--version` optional flag to `gnatss` root command
=> feat: Add flag '--version' to get software version

src/gnatss/solver/utilities.py
This PR updates the remove outliers message with the inclusion of `--remove-outliers` flag. Closes #247
=> chore: Update outliers message to use --remove-outliers flag

src/gnatss/posfilter/__init__.py
I made it so it's easier to get kalman filter.
=> refactor: Simplify the posfilter module to get at kf, si, rot

.github/workflows/ci.yaml, noxfile.py, tests/data/.gitignore
=> ci: Update nox to pull test data and update ci to use nox

.github/workflows/ci.yaml
This PR hopefully fix codecov not reporting correctly on main.
=> ci: Fix codecov action step

.gitignore, .readthedocs.yml, docs/_toc.yml, docs/api.rst, docs/configs.rst, docs/dataspec.rst, noxfile.py, pyproject.toml
Updates the documentations for current functions.
This includes tweaks to the api.rst to automatically create API Documentation from docstrings.
Additionally, the following changes has been made:
- config.rst: Added posfilter and transponders modules
- dataspec.rst: Added data specification v1
- noxfile.py: Added a docs session with separated setup and build step
- readthedocs: Updated rtd to use nox for setting up docs
=> docs: Update docs to reflect current functions

src/gnatss/main.py
Update the documentation for main function to run gnatss
=> docs: Update main docstring for run_gnatss
